name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.21.3'
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
